### ISSUE TITLE
Use CI/hooks to generate Multiversum JSON.

### ISSUE THREAD

**Issue by Paradyx** [RPGLibrarium/web#4]
Webhooks are fun and this would automate some work of the "Multiversum Redaktion"

**Comment by sudo42** [comment]
This should be possible with a little bit of effort.

~Doesn't this belong to the Multiversum repo, rather than this one?~
The scripting would likely be done here to import data from github, but should be triggered by a release hook in our Multiversum repository ...

**Comment by Paradyx** [comment]
Yes, or even better, the scripting is done on travis and wie give travis a push key for this repo.

**Comment by sudo42** [comment]
Sure, we could totally do that!
All required information should be extractable from the yaml file headers.

This would probably be a sub-task or follow-up of RPGLibrarium/Multiversum#2

**Comment by Tikrass** [comment]
Publishing an edition of "Multiversum" automatically based on Github-releases raises the following questions, which have to be addressed first: 

-   How do we distinguish between a new release and a redacted version (e.g. hotfixes) ?
-   How do we get structured meta data for `releases.json` from one repository to another? Do we checkout the repository and parse the YAML-Header?
-   We would need a distinguished handling of post-processed PDF-files. 

Since publishing a new edition is an editorial action, it would require human interaction one way or another. Maybe it is a better idea to extend  [RPGLibrarium/Multiversum](https://github.com/RPGLibrarium/Multiversum) by a new deployment script.
